#!/bin/bash
#
# Download and install selected version of K3S.
#

BASE_URL="https://github.com/k3s-io/k3s/releases"
DEST_DIR="/usr/bin"

get_k3s_versions() {
  INST_K3S_VER=""
  LAT_K3S_VER=""
  LAT_K3S_VER="$(curl -sI "$BASE_URL/latest" | awk '$1=="location:" { print $2 }' | rev | cut -d/ -f1 | rev | tr -d '\r')"
  [ -x $DEST_DIR/k3s ] && INST_K3S_VER=$(k3s -v | awk '$1=="k3s" { print $3 }')
  echo "Installed version : ${INST_K3S_VER:-(none)}"
  echo "Latest version    : ${LAT_K3S_VER:-(none)}"
}

case $1 in
  -i|--install)
    get_k3s_versions
    K3S_VERSION=${2:-$LAT_K3S_VER}
    if [ "$K3S_VERSION" == "$INST_K3S_VER" ] ; then
      echo -e "\nRequested version is the same as the installed one."
      exit 0
    fi
    ;;
  "")
    get_k3s_versions
    if [ "$INST_K3S_VER" == "$LAT_K3S_VER"  ]  ; then
      echo -e "\nLatest version is installed."
    else
      echo -e "\nNew version is available. You can install it by running '${0##*/} -i' as root."
    fi
    exit 0
    ;;
  *)
    echo "Download and install K3S binary."
    echo "Usage: ${0##*/} [--help|--install [version]]"
    echo -e "\nVersion example: v1.29.3+k3s1 (see https://github.com/k3s-io/k3s/releases)"
    echo "If no version is specified, the latest one is downloaded."
    exit 0
    ;;
esac

K3S_ARCH=""
case $(uname -m) in
  aarch64)
    K3S_ARCH="-arm64"
    ;;
  arm*)
    K3S_ARCH="-armhf"
    ;;
esac

echo "Installing k3s binary version $K3S_VERSION in $DEST_DIR ..."

f=$(mktemp -p $DEST_DIR -t k3s.XXXXXXXX)
if [ -z "$f" ] ; then
  echo "Error: cannot create temporary file. Installation failed." > /dev/stderr
  exit 2
fi

wget -qO $f "${BASE_URL}/download/${K3S_VERSION/+/%2B}/k3s$K3S_ARCH"
if file $f | fgrep -qw ELF ; then
  cat $f > $DEST_DIR/k3s
  chown root:root $DEST_DIR/k3s
  chmod 755 $DEST_DIR/k3s
  rm -f $f
else
  echo "Error: downloaded file is not in ELF format. Installation failed." > /dev/stderr
  rm -f $f
  exit 3
fi

/usr/bin/k3s completion bash > /etc/bash_completion.d/k3s

echo "Installation completed successfully."

echo -e "\nVersion installed:"
/usr/bin/k3s -v
